---
  - name: Clone helper scripts
    hosts: all
    become: yes
    tasks:
      - name: Update repository
        apt_repository:
          repo: 'ppa:git-core/ppa'
          state: present
      - name: Install git
        apt:
          name: git
          state: present
          update_cache: yes
      - name: Clone repo
        git:
          repo: git@github.com:mkoshtenko/russian-website-go-fck-yourself.git

